version: 2

registries:
  github:
    type: git
    url: https://github.com/
    username: x-access-token
    password: ${{ secrets.MAINTAINER_PAT }}

updates:

  # Maintain private dependencies for Autofolio
  - package-ecosystem: gomod
    directory: "/.config"
    schedule: 
      interval: daily
    registries:
      - github

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
