---
name: Deploy to PRE-PRODUCTION

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
        description: "Produced name artifact."
      # To avoid being billed 360 minutes if a step does not terminate
      timeout:
        description: "The timeout of the ci job. Default is 25min"
        default: 25
        type: number

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cd-preprod:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pre-production
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PRE-PRODUCTION (GitHub Pages)
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ inputs.artifact_name }}
