---
name: Deploy to PRODUCTION

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
        description: "Produced name artifact."
      # To avoid being billed 360 minutes if a step does not terminate
      timeout:
        description: "The timeout of the ci job. Default is 25min"
        default: 25
        type: number

env:
  HUGO_VERSION: 0.111.3

jobs:
  deploy:
    environment:
      name: production
      url: https://www.xavierbrassoud.fr/
    concurrency:
      group: production
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact '${{ inputs.artifact_name }}'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: .hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
      
      - name: Add SSH Go Module Private Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add - <<< "${{ secrets.VERTICA_PRIVATE_KEY }}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
  
      - name: Setup access for private go modules
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/

      - name: Distribute with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          TZ: America/Los_Angeles
        run: cd .hugo && hugo --gc --minify --baseURL ${{ vars.PROD_BASE_URL }}

      - name: Install lftp
        run: sudo apt install lftp

      - name: Deploy to PRODUCTION
        run: >
          mkdir -p ${{ inputs.artifact_name }} ~/.ssh && touch ~/.ssh/known_hosts &&
          ssh-keyscan -H ${{ secrets.PROD_FTP_SERVER }} >> ~/.ssh/known_hosts &&
          lftp
          -e "set dns:order inet; set file:charset utf8; mirror -Rv --parallel=10 -p .hugo/public/ .; bye;"
          -u ${{ secrets.PROD_FTP_USERNAME }},${{ secrets.PROD_FTP_PASSWORD }}
          sftp://${{ secrets.PROD_FTP_SERVER }}

