# Test new changes against PRE-PROD
---

name: Integration

on:
  push:
    branches:
      - main
      - genesis
  pull_request:
    branches:
      - main
      - genesis

# PRE-PRODUCTION permissions (depends on github-pages)
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci-build:
    uses:
      ./.github/workflows/_ci_ui_build.yml
    with:
      artifact_name: autofolio
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write

  cd-preprod:
    needs: [ci-build]
    uses:
      ./.github/workflows/_cd_preprod.yml
    with:
      artifact_name: autofolio
    secrets: inherit
 