on:
  push:
    branches:
      - main
      - genesis

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:

  release-please:
    runs-on: ubuntu-22.04
    steps:
      # Add packages to update into release-please-config.json
      - name: Write new version to packages
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MAINTAINER_PAT }}
          config-file: .config/release-please-config.json
          manifest-file: .config/.release-please-manifest.json
          target-branch: ${{ github.ref_name }}
